services:
  backend:
    container_name: mt-asset-service-backend
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-local}/multi-tenant-asset-service:latest
    build:
      context: .
      target: development
    pull_policy: missing
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - postgres
      - redis
      - mongodb

  postgres:
    container_name: mt-asset-service-postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: mt-asset-service-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    container_name: mt-asset-service-mongodb
    image: mongo:7
    ports:
      - "27017:27017"
    env_file:
      - .env.development
    volumes:
      - mongodb_data:/data/db
      
volumes:
  postgres_data:
  redis_data:
  mongodb_data:
